### ISSUE TITLE
ansible-playbook start processes

### ISSUE THREAD

**Issue by salpalvv** [salpalvv/darkstar-server#4]
the upstart scripts still don't start the services properly. fix it.

**Comment by salpalvv** [comment]
they are working now. moving to test.

**Comment by Broeks** [comment]
My client wouldn't load when I booted up the server.

**Comment by salpalvv** [comment]
I fixed it. rebooting mysql as a handler was breaking the processes starting. refactored to restart in the playbook instead of at the end. processes are still running after the playbook completes.

**Comment by salpalvv** [comment]
confirmed working.
